### ISSUE TITLE
ConnectedObservableCollection not found

### ISSUE THREAD

**Issue by rudkjobing** [MikeCodesDotNet/Bait-News#3]
Hi Mike.

I am trying to run the project but the compiler can't find ConnectedObservableCollection. Can you tell me what I am missing?

**Comment by MikeCodesDotNet** [comment]
aah, 

It's in the 1.1 branch of ASH (App Service Helper). You can grab a copy from the repository or give me a week and we'll have 1.1 released.

**Comment by MikeCodesDotNet** [comment]
This is now resolved. It was all based on ASH 1.1 previews which were packages incorrectly.
